cols = "route_long_name,route_type,route_text_color,agency_id,route_id,route_color,route_desc,route_url,route_short_name"
routes = [
    "Boulder / Lafayette via Louisville,3,FFFFFF,RTD,DASH_merged_111120851,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,DASH",
    "Flatiron Flyer,3,FFFFFF,RTD,FF6,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF6",
    "Boulder / Lafayette via Baseline,3,FFFFFF,RTD,225E,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,225E",
    "Boulder / Lafayette via Baseline,3,FFFFFF,RTD,225D,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,225D",
    "Flatiron Flyer,3,FFFFFF,RTD,FF3,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF3",
    "Flatiron Flyer,3,FFFFFF,RTD,FF2,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF2",
    "Pearl / Eisenhower / Fairview H.S.,3,FFFFFF,RTD,206F,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,206F",
    "Boulder / Lafayette via Louisville,3,FFFFFF,RTD,DASH_merged_111120857,0099CC,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,DASH",
    "Hampden/Tower,3,FFFFFF,RTD,133,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,133",
    "East Iliff / Seven Hills,3,FFFFFF,RTD,131,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,131",
    "Yale / Buckley,3,FFFFFF,RTD,130,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,130",
    "Smoky Hill Road,3,FFFFFF,RTD,135,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,135",
    "Quincy Avenue,3,FFFFFF,RTD,139,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,139",
    "University Blvd,3,FFFFFF,RTD,24,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,24",
    "Yale Avenue,3,FFFFFF,RTD,27,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,27",
    "20th Avenue,3,FFFFFF,RTD,20,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,20",
    "Evans Avenue,3,FFFFFF,RTD,21,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,21",
    "Boulder / DIA,3,FFFFFF,RTD,AB1,57C1E9,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,AB1",
    "Brighton / Denver,3,FFFFFF,RTD,RX,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,RX",
    "Riverbend,3,FFFFFF,RTD,29,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,29",
    "Union Station to Jefferson County Government Center-Golden Station,0,FFFFFF,RTD,103W,009DAA,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,W",
    "South Broadway,3,FFFFFF,RTD,0,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,0",
    "Wildcat Crosstown,3,FFFFFF,RTD,403,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,403",
    "Morrison Road,3,FFFFFF,RTD,4,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,4",
    "Highlands Ranch/Mineral,3,FFFFFF,RTD,401,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,401",
    "Brighton / Denver,3,FFFFFF,RTD,RC,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,RC",
    "North Broadway / Huron,3,FFFFFF,RTD,8,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,8",
    "Flatiron Flyer,3,FFFFFF,RTD,FF5,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF5",
    "Flatiron Flyer,3,FFFFFF,RTD,FF4,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF4",
    "Golden / Boulder,3,FFFFFF,RTD,GS,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,GS",
    "28th Avenue,3,FFFFFF,RTD,28B,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,28B",
    "Lincoln Station to Peoria Station,0,000000,RTD,107R,C4D600,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,R",
    "Longmont / Denver,3,FFFFFF,RTD,L,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,L",
    "120th Avenue / Brighton,3,FFFFFF,RTD,120,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,120",
    "Peoria Street,3,FFFFFF,RTD,121,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,121",
    "Boulder / Longmont,3,FFFFFF,RTD,BOLT,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,BOLT",
    "Broomfield / Wagon Road,3,FFFFFF,RTD,128,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,128",
    "Boulder / Lafayette via Arapahoe,3,FFFFFF,RTD,JUMP_merged_111120849,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,JUMP",
    "CU / Thunderbird,3,FFFFFF,RTD,209G,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,209G",
    "Broadway,3,FFFFFF,RTD,SKIP_merged_111120852,0099CC,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,SKIP",
    "West Bowles,3,FFFFFF,RTD,59,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,59",
    "Highlands Ranch Parkway,3,FFFFFF,RTD,402L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,402L",
    "Sheridan Blvd,3,FFFFFF,RTD,51,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,51",
    "Lakes Crosstown,3,FFFFFF,RTD,50,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,50",
    "W 52nd Avenue / South Bannock,3,FFFFFF,RTD,52,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,52",
    "Cherry Creek / Parker Rd Limited,3,FFFFFF,RTD,83L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,83L",
    "Union Station to Denver Airport Station,2,FFFFFF,RTD,A,57C1E9,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,A",
    "South Kipling Limited,3,FFFFFF,RTD,100L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,100L",
    "Northglenn/Comm City/Central Park,3,FFFFFF,RTD,88,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,88",
    "Stapleton / Anschutz Campus,3,FFFFFF,RTD,89,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,89",
    "East Alameda Limited,3,FFFFFF,RTD,3L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,3L",
    "80th Avenue,3,FFFFFF,RTD,80,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,80",
    "30th Street,3,FFFFFF,RTD,BOND_merged_111120847,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,BOUND",
    "Free MetroRide,3,FFFFFF,RTD,FMR_merged_111120848,00A19B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,FREE METRORIDE",
    "US36 & Sheridan Limited,3,FFFFFF,RTD,90L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,90L",
    "Chatfield Avenue,3,FFFFFF,RTD,85,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,85",
    "Broadway,3,FFFFFF,RTD,SKIP_merged_111120846,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,SKIP",
    "Boulder / Lafayette via Arapahoe,3,FFFFFF,RTD,JUMP_merged_111120855,0099CC,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,JUMP",
    "Alameda Avenue,3,FFFFFF,RTD,3,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,3",
    "South Federal Limited,3,FFFFFF,RTD,30L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,30L",
    "Union Station to Westminster Station,2,FFFFFF,RTD,113B,4E9D2D,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,B",
    "Longmont / Denver,3,FFFFFF,RTD,LSX,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,LSX",
    "Fort Logan Limited,3,FFFFFF,RTD,36L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,36L",
    "18th & California Station to Florida Station,0,FFFFFF,RTD,101H,0075BE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,H",
    "Free Mall Ride,3,FFFFFF,RTD,MALL,675DC6,,http://www.rtd-denver.com/Schedules.shtml,MALLRIDE",
    "30th & Downing Station to Littleton-Mineral Station,0,FFFFFF,RTD,101D,008348,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,D",
    "Union Station to Lincoln Station,0,FFFFFF,RTD,101E,552683,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,E",
    "18th & California Station to Lincoln Station,0,FFFFFF,RTD,101F,EE3E33,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,F",
    "Union Station to Littleton-Mineral Station,0,FFFFFF,RTD,101C,F79239,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,C",
    "Evergreen / Aspen Park / Denver,3,FFFFFF,RTD,EX,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,EX",
    "Cherry Creek / Parker Rd Limited,3,FFFFFF,RTD,83D,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,83D",
    "Kipling Street,3,FFFFFF,RTD,100,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,100",
    "Evergreen / Aspen Park / Denver,3,FFFFFF,RTD,EV,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,EV",
    "Evergreen / Aspen Park / Denver,3,FFFFFF,RTD,ES,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,ES",
    "Havana Street,3,FFFFFF,RTD,105,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,105",
    "West 38th Avenue,3,FFFFFF,RTD,38,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,38",
    "West 32nd Avenue / City Park,3,FFFFFF,RTD,32,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,32",
    "Federal Blvd,3,FFFFFF,RTD,31,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,31",
    "South Federal Blvd,3,FFFFFF,RTD,30,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,30",
    "Smith Road Industrial,3,FFFFFF,RTD,37,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,37",
    "Fort Logan,3,FFFFFF,RTD,36,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,36",
    "Hampden Avenue,3,FFFFFF,RTD,35,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,35",
    "North Colorado Limited,3,FFFFFF,RTD,39L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,39L",
    "North Federal Limited,3,FFFFFF,RTD,31L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,31L",
    "72nd Avenue,3,FFFFFF,RTD,72,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,72",
    "1st Avenue,3,FFFFFF,RTD,1W,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,1W",
    "Arapahoe County / DIA,3,FFFFFF,RTD,ATA,57C1E9,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,ATA",
    "28th Avenue,3,FFFFFF,RTD,28,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,28",
    "Quaker via Ward Limited,3,FFFFFF,RTD,72L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,72L",
    "72nd Avenue,3,FFFFFF,RTD,72W,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,72W",
    "Commerce City/ Dicks SG Park,3,FFFFFF,RTD,62,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,62",
    "CU East Campus,3,FFFFFF,RTD,STMP_merged_111120850,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,STAMPEDE",
    "Monaco Parkway,3,FFFFFF,RTD,65,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,65",
    "Arapahoe Road,3,FFFFFF,RTD,66,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,66",
    "Ridge Road,3,FFFFFF,RTD,67,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,67",
    "Brighton / Denver Airport,3,FFFFFF,RTD,145X,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,145X",
    "West Colfax Limited,3,FFFFFF,RTD,16L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,16L",
    "Longmont / Denver,3,FFFFFF,RTD,LNX,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,LNX",
    "30th Street,3,FFFFFF,RTD,BOND_merged_111120853,0099CC,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,BOUND",
    "South Broadway Limited,3,FFFFFF,RTD,0L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,0L",
    "East 6th Avenue,3,FFFFFF,RTD,6,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,6",
    "Commerce City / Denver Express,3,FFFFFF,RTD,104X,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,104X",
    "28th St / Gunbarrel / Heatherwood,3,FFFFFF,RTD,205T,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,205T",
    "Longmont / East Boulder / CU,3,FFFFFF,RTD,J,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,J",
    "Nederland / Boulder,3,FFFFFF,RTD,N,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,N",
    "Pine Junction / Conifer / Denver,3,FFFFFF,RTD,CX,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,CX",
    "Buckley Road,3,FFFFFF,RTD,169,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,169",
    "Louisville / Broomfield,3,FFFFFF,RTD,228,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,228",
    "Pine Junction / Conifer / Denver,3,FFFFFF,RTD,CS,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,CS",
    "Boulder / Lafayette via Baseline,3,FFFFFF,RTD,225,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,225",
    "92nd Avenue,3,FFFFFF,RTD,92,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,92",
    "Pine Junction / Conifer / Denver,3,FFFFFF,RTD,CV,64A70B,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,CV",
    "Mississippi Avenue,3,FFFFFF,RTD,11,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,11",
    "East 12th Avenue,3,FFFFFF,RTD,10,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,10",
    "Downing / N Washington,3,FFFFFF,RTD,12,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,12",
    "East Colfax Avenue,3,FFFFFF,RTD,15,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,15",
    "West Florida Avenue,3,FFFFFF,RTD,14,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,14",
    "Red Rocks College,3,FFFFFF,RTD,17,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,17",
    "West Colfax Avenue,3,FFFFFF,RTD,16,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,16",
    "North Pecos,3,FFFFFF,RTD,19,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,19",
    "Flatiron Flyer,3,FFFFFF,RTD,FF1,005798,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,FF1",
    "Wagon Road / Civic Center Express,3,FFFFFF,RTD,122X,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,122X",
    "CU East Campus,3,FFFFFF,RTD,STMP_merged_111120856,0099CC,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,STAMPEDE",
    "Platte Valley,3,FFFFFF,RTD,33A,0076CE,This Route Travels Clock-wise & Counter clock-wise,http://www.rtd-denver.com/Schedules.shtml,33A",
    "Platte Valley,3,FFFFFF,RTD,33B,0076CE,This Route Travels Clock-wise & Counter clock-wise,http://www.rtd-denver.com/Schedules.shtml,33B",
    "Chambers Road,3,FFFFFF,RTD,153,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,153",
    "CCA / Buckley,3,FFFFFF,RTD,157,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,157",
    "West 80th Limited,3,FFFFFF,RTD,80L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,80L",
    "West 112th Avenue,3,FFFFFF,RTD,112,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,112",
    "Anschutz Shuttle,3,000000,RTD,SHUZ,FFFF00,,http://www.rtd-denver.com/Schedules.shtml,ANSCHUTZ SHUTTLE",
    "Bruce Randolph Ave,3,FFFFFF,RTD,34,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,34",
    "Iris / Valmont,3,FFFFFF,RTD,208F,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,208F",
    "West 104th Avenue,3,FFFFFF,RTD,104,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,104",
    "East 48th Avenue / Commerce City,3,FFFFFF,RTD,48,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,48",
    "South Dahlia,3,FFFFFF,RTD,46,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,46",
    "44th Avenue,3,FFFFFF,RTD,44,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,44",
    "Montbello via 51st/GVR,3,FFFFFF,RTD,45,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,45",
    "Montbello via Albrook/GVR,3,FFFFFF,RTD,42,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,42",
    "Martin Luther King Blvd,3,FFFFFF,RTD,43,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,43",
    "Colorado Boulevard,3,FFFFFF,RTD,40,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,40",
    "1st Avenue,3,FFFFFF,RTD,1,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,1",
    "Skyline Crosstown,3,FFFFFF,RTD,323,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,323",
    "Boulder / DIA,3,FFFFFF,RTD,AB2,57C1E9,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,AB2",
    "Westside Crosstown,3,FFFFFF,RTD,326,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,326",
    "Eastside Crosstown,3,FFFFFF,RTD,327,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,327",
    "Main Street,3,FFFFFF,RTD,324,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,324",
    "West 10th Avenue,3,FFFFFF,RTD,9,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,9",
    "Longmont / Denver,3,FFFFFF,RTD,LX,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,LX",
    "Wagon Road / Denver Airport,3,FFFFFF,RTD,AA,57C1E9,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,AA",
    "Boulder / DIA,3,FFFFFF,RTD,AB,57C1E9,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,AB",
    "28th St / Gunbarrel / Heatherwood,3,FFFFFF,RTD,205,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,205",
    "Table Mesa / Moorhead / North 19th,3,FFFFFF,RTD,204,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,204",
    "Pearl / Eisenhower / Fairview H.S.,3,FFFFFF,RTD,206,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,206",
    "CU / Thunderbird,3,FFFFFF,RTD,209,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,209",
    "Iris / Valmont,3,FFFFFF,RTD,208,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,208",
    "Buckley / Tower DIA Limited,3,FFFFFF,RTD,169L,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,169L",
    "Ken Caryl Avenue,3,FFFFFF,RTD,77,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,77",
    "Wadsworth Blvd,3,FFFFFF,RTD,76,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,76",
    "South Wadsworth Limited,3,FFFFFF,RTD,87L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,87L",
    "Quebec Street,3,FFFFFF,RTD,73,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,73",
    "Arapahoe County / DIA,3,FFFFFF,RTD,AT,57C1E9,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,AT",
    "Boulder Circulator,3,FFFFFF,RTD,HOP,0099CC,This Route Travels Clock-wise & Counter clock-wise,http://www.rtd-denver.com/Schedules.shtml,HOP",
    "Lyons / Boulder,3,FFFFFF,RTD,Y,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,Y",
    "Parker Road - Lincoln Ave,3,FFFFFF,RTD,483,0076CE,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,483",
    "ART,3,000000,RTD,ART,FFFF00,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,ART",
    "Wagon Road / Thornton Express,3,FFFFFF,RTD,120X,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,120X",
    "Free MetroRide,3,FFFFFF,RTD,FMR_merged_111120854,00A1A5,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,FREE METRORIDE",
    "Parker / Denver,3,FFFFFF,RTD,P,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,P",
    "South Simms Express,3,FFFFFF,RTD,116X,64A70B,This Route Travels Northbound & Southbound,http://www.rtd-denver.com/Schedules.shtml,116X",
    "Olde Town Arvada Special,3,FFFFFF,RTD,55S,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,55S",
    "Olde Town Arvada Limited,3,FFFFFF,RTD,55L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,55L",
    "East Colfax Limited,3,FFFFFF,RTD,15L,0076CE,This Route Travels Eastbound & Westbound,http://www.rtd-denver.com/Schedules.shtml,15L"
]

valid_routes = ["A", "B", "C", "D", "E", "F", "H", "R", "W"]

col_list = cols.split(",")
statement = """
  INSERT INTO routes (
    route_long_name,
    route_type,
    route_text_color,
    agency_id,
    route_id,
    route_color,
    route_desc,
    route_url,
    route_short_name
  ) VALUES
"""
for route in routes:
    info = route.split(",")
    route_id = info[8]
    if route_id in valid_routes:
        statement += " ( "
        print info[0]
        for index in range(len(col_list)):
            if index != 1:
                statement += "'" + info[index] + "'"
            else:
                statement += info[index]

            if index != len(col_list) - 1:
                statement += ", "

        statement += " ), "

statement = statement[:len(statement) - 2]
statement += ";"
#print statement





#"block_id,route_id,direction_id,trip_headsign,shape_id,service_id,trip_id"
#"a_101 15,101C,1,C-Line Mineral,979138,FR_merged_111120859,110851898"
#
#trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
#110851898,07:19:30,07:19:30,25434,1,,,1,,
#110851898,07:21:00,07:21:00,25433,2,,,,,
#110851898,07:22:30,07:22:30,25432,3,,,,,
#110851898,07:24:30,07:24:30,25431,4,,,,,
#110851898,07:27:30,07:27:30,23059,5,,,,,
#110851898,07:30:30,07:30:30,23060,6,,,,,
#110851898,07:32:00,07:32:30,23061,7,,,,,
#110851898,07:35:15,07:35:15,25435,8,,,,,
#110851898,07:38:00,07:38:00,25436,9,,,,,
#110851898,07:40:00,07:40:00,25437,10,,,,,
#110851898,07:43:00,07:43:00,25438,11,,,,,
#110851898,07:47:30,07:47:30,25439,12,,1,,,
